version: "3"

services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: "ganache-cli -d -m witch collapse practice feed shame open despair creek road again ice least -l 20000000"
